import fs from "node:fs";
import path from "node:path";
import { type ComposeProject, parseEnvFile } from "./env-files";
import { dockerDir } from "./paths";

const PLACEHOLDER = /\$\{([A-Za-z_][A-Za-z0-9_]*)\}/g;

function expandTemplate(text: string, env: Record<string, string>): string {
  let body = text;
  for (let i = 0; i < 8; i++) {
    const next = body.replace(PLACEHOLDER, (_, key: string) => {
      if (!(key in env)) {
        throw new Error(`render-env: unset placeholder \${${key}}`);
      }
      return env[key];
    });
    if (next === body) break;
    body = next;
  }
  const unresolved = [...body.matchAll(PLACEHOLDER)].map((m) => m[1]);
  if (unresolved.length > 0) {
    throw new Error(
      `render-env: unresolved placeholders: ${[...new Set(unresolved)].sort().join(", ")}`,
    );
  }
  return body;
}

function stripLeadingComments(body: string): string {
  const lines = body.split(/\n/);
  while (
    lines.length > 0 &&
    (lines[0].startsWith("#") || lines[0].trim() === "")
  ) {
    lines.shift();
  }
  return lines.join("\n");
}

/** Render `.docker/env/<project>.env` from profile + template. */
export function renderProjectEnv(project: ComposeProject): string {
  const profilePath = path.join(dockerDir, "env/profiles", `${project}.env`);
  const templatePath = path.join(dockerDir, "env/template.env");
  const outPath = path.join(dockerDir, "env", `${project}.env`);

  if (!fs.existsSync(profilePath)) {
    const profilesDir = path.join(dockerDir, "env/profiles");
    const available = fs.existsSync(profilesDir)
      ? fs
          .readdirSync(profilesDir)
          .filter((f) => f.endsWith(".env"))
          .join(", ")
      : "(none)";
    throw new Error(`missing profile: ${profilePath}\nAvailable: ${available}`);
  }
  if (!fs.existsSync(templatePath)) {
    throw new Error(`missing template: ${templatePath}`);
  }

  const env: Record<string, string> = {
    ...parseEnvFile(fs.readFileSync(profilePath, "utf8")),
    COMPOSE_PROJECT_NAME: project,
  };

  const template = fs.readFileSync(templatePath, "utf8");
  let body = expandTemplate(template, env);
  body = stripLeadingComments(body);

  const header =
    "# Generated by pnpm run task -- render-env — do not edit.\n" +
    `# Profile: .docker/env/profiles/${project}.env\n\n`;

  const output = body.endsWith("\n") ? header + body : `${header + body}\n`;
  fs.writeFileSync(outPath, output, "utf8");
  return outPath;
}
